import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  overlay: {
    position: 'absolute',
    justifyContent: 'center',
    left: 20,
    right: 0,
    top: 0,
    height: '30%',
    opacity: 1,
  },
  overlaybutton: {
    position: 'absolute',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    alignContent: 'center',
  },
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5fcff',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  backImage: {
    height: '100%',
    width: '100%',
    marginTop: 0,
    alignItems: 'center',
  },
  viewSwiper: {
    height: '75%',
    width: '100%',
    overflow: 'hidden',
  },
  slide1: {
    flex: 1,
    backgroundColor: '#rgba(0,0,0,0)',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  slider1text1come: {
    color: '#fff',
    fontSize: 44,
    fontFamily: 'Gilroy-SemiBold',
    // textShadowColor: 'rgba(0, 0, 0, 0.9)',
    // textShadowOffset: {width: -1, height: 1},
    // textShadowRadius: 10
  },
  slider1text1closly: {
    color: '#fff',
    fontSize: 44,
    fontFamily: 'Gilroy-SemiBold',
  },
  slider1text2: {
    color: '#fff',
    fontSize: 32,
    fontFamily: 'Gilroy-SemiBold',
  },
  slider1text3: {
    color: '#fff',
    fontSize: 20,
    fontFamily: 'Poppins-Regular',
    textAlign: 'left',
  },
  slider1View1: {
    justifyContent: 'center',
    marginTop: 0,
    marginLeft: 20,
    marginRight: 0,
    width: '100%',
    height: '25%',
  },
  slider1View2: {
    margin: 20,
    width: '90%',
    marginTop: '72%',
    overflow: 'hidden',
  },
  slide2: {
    flex: 1,
    backgroundColor: '#rgba(0,0,0,0)',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  slide3: {
    flex: 1,
    backgroundColor: '#rgba(0,0,0,0)',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  paginationStyle: {
    bottom: 0,
    left: 20,
  },
  activeDots: {
    backgroundColor: '#FF2485',
    width: 16,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  normalDots: {
    backgroundColor: '#FF2485',
    width: 16,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  viewfullCover: {
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
  },
  viewButtons: {
    height: '25%',
    width: '100%',
  },
  viewlogin: {
    height: '40%',
    width: '100%',
    justifyContent: 'center',
  },
  viewFnT: {
    height: '40%',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonLogin: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '70%',
    margin: 20,
    backgroundColor: '#FF2485',
    borderRadius: 30,
    overflow: 'hidden',
  },
  txtLogin: {
    color: '#FFFFFF',
    alignSelf: 'center',
    fontFamily: 'Gilroy-Bold',
    fontSize: 15,
  },
  buttonFacebook: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '70%',
    marginRight: 20,
    width: '40%',
    backgroundColor: '#157DC3',
    borderRadius: 30,
    overflow: 'hidden',
  },
  imageTwitter: {
    width: 20,
    height: 20,
  },
  buttonTwitter: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '70%',
    marginLeft: 20,
    width: '40%',
    backgroundColor: '#1DA1F3',
    borderRadius: 30,
    overflow: 'hidden',
  },
  selectedDotView: {
    backgroundColor: '#FF2485',
    width: 16,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  unselectedDotView: {
    backgroundColor: '#FFFFFF',
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
});
