import {StyleSheet, Dimensions} from 'react-native';
const SCREEN_WIDTH = Dimensions.get('window').width;
const ITEM_WIDTH = Math.round(SCREEN_WIDTH * 0.9);
const ITEM_HEIGHT = Math.round(ITEM_WIDTH * 0.57);

export default StyleSheet.create({
  homeNavigationImage: {
    height: '35%',
    width: '100%',
    marginTop: 0,
    resizeMode: 'cover',
  },
  cellMsgTxt: {
    color: '#8895AA',
    padding: 0,
    height: '100%',
    width: '100%',
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
  },
  cellMsgMainView: {
    width: '100%',
    height: '50%',
    justifyContent: 'center',
  },
  cellUserTxt: {
    color: '#121212',
    padding: 0,
    height: '100%',
    width: '100%',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 17,
  },
  cellUsernameView: {
    width: '100%',
    height: '50%',
    justifyContent: 'flex-start',
  },
  cellCenterMainView: {
    marginLeft: 8,
    flex: 1,
    height: '100%',
    alignSelf: 'flex-start',
  },
  cellUnreadCountTxt: {
    color: '#ffffff',
    alignSelf: 'center',
    marginTop: 4,
    fontSize: 17,
    fontFamily: 'Poppins-SemiBold',
  },
  cellUnreadCountView: {
    backgroundColor: '#7D00E7',
    alignSelf: 'center',
    padding: 0,
    height: '70%',
    width: '50%',
    borderRadius: 12,
  },
  cellUnreadCountMainView: {
    flexDirection: 'column',
    width: '25%',
    height: '70%',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  cellDateTxt: {
    color: '#8895AA',
    padding: 0,
    height: '100%',
    width: '100%',
    fontFamily: 'Poppins-MediumItalic',
    fontSize: 10,
    marginTop: 3,
    marginRight: 10,
  },
  cellDateView: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginRight: 5,
    position: 'absolute',
  },
  cellRightMainView: {
    flexDirection: 'row-reverse',
    flex: 1,
    alignContent: 'flex-start',
  },
  cellProfileImage: {
    aspectRatio: 1,
    borderRadius: 50,
    overflow: 'hidden',
    height: '100%',
    marginLeft: 10,
    justifyContent: 'center',
  },
  cellProfileView: {
    flexDirection: 'row',
    width: '100%',
    height: 60,
    justifyContent: 'center',
  },
  mainCellView: {
    width: '100%',
    height: 70,
    justifyContent: 'flex-end',
  },
  viewSwiper: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    backgroundColor: '#rgba(0,0,0,0)',
  },
  itemContainer: {
    width: ITEM_WIDTH,
    height: ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 10,
    paddingRight: 10,
  },
  viewUpcomingEvent: {
    width: Math.round(SCREEN_WIDTH * 0.38),
    justifyContent: 'center',
    overflow: 'hidden',
  },
  container: {
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'white',
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  backImage: {
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  viewHeader: {
    height: 64,
    width: '100%',
    marginTop: 0,
    flexDirection: 'row',
  },
  messageView: {
    justifyContent: 'center',
    height: '100%',
    marginLeft: 20,
    fontSize: 30,
  },
  messageText: {
    fontSize: 30,
    color: 'white',
    fontFamily: 'Gilroy-Bold',
  },
  storiesText: {
    fontSize: 15,
    color: 'white',
    fontFamily: 'Poppins-SemiBold',
    alignSelf: 'flex-end',
    marginBottom: -10,
  },
  cameraMainView: {
    width: Math.round(SCREEN_WIDTH * 0.35),
    height: '85%',
    paddingHorizontal: 10,
    justifyContent: 'center',
    overflow: 'hidden',
    alignItems: 'center',
    alignSelf: 'center',
  },
  cameraGradientView: {
    width: '100%',
    height: '80%',
    justifyContent: 'center',
    backgroundColor: 'dodgerblue',
    borderRadius: 15,
    overflow: 'hidden',
    alignItems: 'center',
  },
  cameraTitleView: {
    width: '100%',
    aspectRatio: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraTitleText: {
    alignSelf: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  cameraImage: {
    resizeMode: 'contain',
    width: 50,
    height: 50,
  },
  storiesProfileImageItem: {
    flex: 1,
    borderRadius: 15,
    margin: 10,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storiesItemTitleView: {
    width: '100%',
    aspectRatio: 6,
  },
  storiesItemTitleText: {
    alignSelf: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  storiesMainView: {
    width: '100%',
    aspectRatio: 1.5,
  },
});
