import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  followTxt: {
    fontSize: 15,
    marginLeft: 15,
  },
  listView: {
    flexDirection: 'row',
    width: wp('100%'),
  },
  searchIcon: {
    width: wp('3%'),
    height: hp('3%'),
    resizeMode: 'contain',
    justifyContent: 'flex-end',
    position: 'absolute',
    right: 10,
    marginRight: '3%',
  },
  descriptionView: {
    height: '70%',
    width: '100%',
    borderRadius: 35,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      height: 0.5,
      width: 0.5,
    },
    justifyContent: 'center',
  },
  searchMainView: {
    width: '90%',
    height: '10%',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
  },
  accountsTxt: {
    textAlign: 'center',
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
    color: 'white',
  },
  accountsView: {
    shadowColor: '#000000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {height: 0.5, width: 0.5},
    backgroundColor: '#FF2485',
    justifyContent: 'center',
    width: '90%',
    height: '62%',
    alignSelf: 'flex-end',
    borderRadius: 31,
  },
  accountsMainView: {
    width: '50%',
    height: '100%',
    justifyContent: 'center',
  },
  eventTxt: {
    textAlign: 'center',
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
  },
  eventView: {
    shadowColor: '#000000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {height: 0.5, width: 0.5},
    justifyContent: 'center',
    width: '90%',
    height: '62%',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderRadius: 31,
  },
  eventMainView: {
    width: '50%',
    height: '100%',
    justifyContent: 'center',
  },
  segMainView: {
    width: '90%',
    height: '8%',
    marginTop: '-7%',
    alignSelf: 'center',
    flexDirection: 'row',
  },
  safeView: {
    height: '100%',
    width: '100%',
    alignSelf: 'flex-start',
    backgroundColor: 'white',
  },
  mainView: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  homeNavigationImg: {
    height: '60%',
    width: '100%',
    position: 'absolute',
  },
  closeImg: {
    alignSelf: 'center',
    height: '70%',
    width: '70%',
    aspectRatio: 1,
  },
  closeView: {
    height: '45%',
    aspectRatio: 1,
    alignContent: 'center',
    flexDirection: 'row',
    alignSelf: 'flex-end',
    marginRight: 20,
  },
  findUserTxt: {
    height: '100%',
    marginLeft: 20,
    fontSize: 30,
    color: 'white',
    fontFamily: 'Gilroy-Bold',
  },
  findUserView: {
    height: '60%',
    width: '100%',
    alignContent: 'center',
    flexDirection: 'row',
  },
  headerMainView: {
    height: '13%',
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0)',
    justifyContent: 'center',
  },
  petName: {
    color: '#8895AA',
    fontSize: 10,
  },
  list: {
    paddingVertical: 4,
    margin: 5,
  },
  userName: {
    color: '#13153B',
    fontSize: 12,
    fontWeight: 'bold',
  },
  listProfileView: {
    width: wp('15%'),
  },
  listProfileImage: {
    width: 54,
    height: 53,
    borderRadius: 60 / 2,
  },
  listTextView: {
    flexDirection: 'column',
    marginLeft: 1,
    justifyContent: 'center',
    width: wp('35%'),
  },
});
