import { StyleSheet } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { getStatusBarHeight } from 'react-native-status-bar-height';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
    paddingBottom: 100
  },
  postMemoryTitleMainView: {
    width: '100%',
    aspectRatio: 1.5,
    marginTop: getStatusBarHeight(),
  },
  postMemoryTitleChildView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backImageMainView: {
    flex: 1,
  },
  backImage: {
    width: wp('100%'),
    height: hp('25%'),
  },
  backGroundImage: {
    width: '100%',
    height: '45%',
    resizeMode: 'cover',
    position: 'absolute',
  },
  overlay: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    position: 'absolute',
  },
  postMemoryTitleContainer: {
    width: wp('95%'),
    height: hp('5%'),
    flexDirection: 'row',
    marginLeft: '3%',
    marginRight: '3%',
    alignItems: 'center',
    marginBottom: '40%',
  },
  postMemoryText: {
    color: 'white',
    fontSize: 25,
    fontWeight: 'bold',
    marginLeft: '1%',
    fontFamily: 'Gilroy-Bold',
  },
  closeIcon: {
    alignSelf: 'center',
    height: '70%',
    width: '70%',
    aspectRatio: 1,
  },
  closeButtonView: {
    height: '60%',
    aspectRatio: 1,
    alignContent: 'center',
    flexDirection: 'row',
    alignSelf: 'flex-end',
  },
  postMemoryScrollView: {
    height: hp('100%'),
    backgroundColor: '#F8F8F8',
    marginTop: '-40%',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderWidth: 1,
    borderColor: '#F8F8F8',
  },
  postMemoryChildScrollView: {
    marginLeft: '5%',
    marginRight: '3%',
    marginBottom: '10%',
  },
  titleMainView: {
    flexDirection: 'row',
    width: '100%',
    height: '17%',
    marginTop: '5%',
    alignItems: 'center',
  },
  titleImageMianView: {
    width: '30%',
    height: '100%',
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  avatarImage: {
    borderRadius: 20,
    height: '103%',
    width: '103%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  textInputMainView: {
    flexDirection: 'column',
    width: '60%',
    height: '100%',
    marginLeft: '10%',
  },
  textInputTitleView: {
    alignSelf: 'flex-end',
    right: 10,
  },
  textTitleView: {
    color: 'gray',
    fontSize: 14,
    fontFamily: 'Gilroy-Medium',
  },
  eventTypeMainView: {
    marginTop: '8%',
  },
  eventTypeText: {
    color: '#BEBEBE',
    fontSize: 14,
    fontFamily: 'Gilroy-Medium',
  },
  descriptionMainView: {
    marginTop: '8%',
  },
  descriptionText: {
    color: '#BEBEBE',
    fontSize: 14,
    fontFamily: 'Gilroy-Medium',
    marginLeft: 5,
  },
  descriptionView: {
    marginTop: '3%',
    width: wp('90%'),
    height: 150,
    borderColor: '#DEDEDE',
    borderWidth: 1,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: 'white',
    borderRadius: 8,
  },
  textArea: {
    height: 150,
    justifyContent: 'flex-start',
    fontSize: 16,
    fontFamily: 'Gilroy-SemiBold',
  },
  titleView: {
    height: 90,
    borderColor: '#DEDEDE',
    borderWidth: 1,
    paddingLeft: 5,
    paddingRight: 5,
    backgroundColor: 'white',
    borderRadius: 8,
    marginTop: 5,
  },
  titleArea: {
    height: 88,
    justifyContent: 'flex-start',
    fontSize: 16,
    fontFamily: 'Gilroy-SemiBold',
  },
  createEventButton: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FF2485',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#FF2485',
    justifyContent: 'center',
    alignItems: 'center',
  },
  createEventButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Gilroy-Bold',
  },
  listcontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  eventTypeListItemView: {
    paddingLeft: 15,
    paddingRight: 15,
    height: 25,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#BEBEBE',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    marginBottom: 10,
    overflow: 'hidden',
  },
  locationTitleMainView: {
    height: 20,
    marginTop: 100,
    justifyContent: 'center',
  },
  loactionTitle: {
    color: '#BEBEBE',
    fontSize: 14,
    fontFamily: 'Gilroy-Medium',
  },
  locationLineView: {
    borderBottomWidth: 1,
    borderBottomColor: 'gray',
    width: '100%',
  },
  locationMainView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationTextInputView: {
    height: 40,
    paddingLeft: 5,
    fontSize: 16,
    paddingRight: 10,
    width: '100%',
    fontFamily: 'Gilroy-SemiBold',
  },
  locationImageView: {
    height: 18,
    width: 18,
    position: 'absolute',
    right: 2,
    resizeMode: 'contain',
  },
  postMemoryMainView: {
    marginTop: '20%',
    alignItems: 'center',
    height: '10%',
    justifyContent: 'center',
  },
  dotsBorders: {
    alignSelf: 'center',
    width: '100%',
    height: '100%',
    borderWidth: 1.5,
    borderRadius: 20,
    borderStyle: 'dashed',
    borderColor: '#EBEBEB',
  },

  borderInsideView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  image: {
    width: 26,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: 20,
    resizeMode: 'contain',
  },
});
