const AppImages = {
  imagePlaceholder: require('@assets/img/imageplaceholder.png'),
  loginImage: require('@assets/img/loginImage.png'),
  faceBook: require('@assets/img/facebook.png'),
  twitter: require('@assets/img/twitter.png'),
  homeNavigation: require('@assets/img/homenavigation.png'),
  otherNavigation: require('@assets/img/othernavigation.png'),
  filledHeart: require('@assets/img/heart.png'),
  outlineHeart: require('@assets/img/heartoutline.png'),
  comment: require('@assets/img/message.png'),
  camera: require('@assets/img/camera.png'),
  eventInfoBackground: require('@assets/img/eventinfoback.png'),
  edit: require('@assets/img/edit.png'),
  increment: require('@assets/img/increment.png'),
  decrement: require('@assets/img/decrement.png'),
  share: require('@assets/img/share.png'),
  close: require('@assets/img/close.png'),
  homefocused: require('@assets/img/homefocused.png'),
  home: require('@assets/img/home.png'),
  search: require('@assets/img/search.png'),
  searchfocused: require('@assets/img/searchfocused.png'),
  plus: require('@assets/img/plus.png'),
  messages: require('@assets/img/messages.png'),
  messagesfocused: require('@assets/img/messagesfocused.png'),
  myprofile: require('@assets/img/myprofile.png'),
  bottombar: require('@assets/img/bottombar.png'),
  menu: require('@assets/img/menu.png'),

  flag: require('@assets/img/flag-pink.png'),

  calendar: require('@assets/img/calendar.png'),
  heartwhite: require('@assets/img/heartwhite.png'),
  logout: require('@assets/img/logout.png'),
  mail: require('@assets/img/mail.png'),
  searchwhite: require('@assets/img/searchwhite.png'),
  settings: require('@assets/img/settings.png'),
  star: require('@assets/img/star.png'),

  facebookcircleicon: require('@assets/img/facebookcircleicon.png'),
  googlecircleicon: require('@assets/img/googlecircleicon.png'),
  twittercircleicon: require('@assets/img/twittercircleicon.png'),

  demoimage: require('@assets/img/demoimage.png'),
  dotview: require('@assets/img/dotview.png'),
  followbutton: require('@assets/img/followbutton.png'),
  followingbutton: require('@assets/img/followingbutton.png'),
  sendmessagebutton: require('@assets/img/sendmessagebutton.png'),
  imageaddButton: require('@assets/img/ImageAddButton.png'),
  location: require('@assets/img/location.png'),

  avata1: require('@assets/img/avata-01.jpeg'),
  avata2: require('@assets/img/avata-02.jpeg'),
  avata3: require('@assets/img/avata-03.jpeg'),
  avata4: require('@assets/img/avata-04.jpeg'),

  sendButton: require('@assets/img/sendButton.png'),
  delete: require('@assets/img/delete.png'),

  about: require('@assets/img/about.png'),
  account: require('@assets/img/account.png'),
  arrowright: require('@assets/img/arrowright.png'),
  help: require('@assets/img/help.png'),
  privacy: require('@assets/img/privacy.png'),
  security: require('@assets/img/security.png'),

  bookmark: require('@assets/img/bookmark.png'),
  folder: require('@assets/img/folder.png'),
  send: require('@assets/img/send.png'),
  locationactivity: require('@assets/img/locationactivity.png'),

  arrowleft: require('@assets/img/arrowleft.png'),
  paymentfailed: require('@assets/img/paymentfailed.png'),
  paymentsuccess: require('@assets/img/paymentsuccess.png'),
  ticketImg: require('@assets/img/ticketImg.png'),

  checkboxSelected: require('@assets/img/checkboxselected.png'),
  checkboxUnselected: require('@assets/img/checkboxunselected.png'),

  entry: require('@assets/img/entry.png'),
  starpink: require('@assets/img/starpink.png'),
  checkedpink: require('@assets/img/checkedpink.png'),
  paypal: require('@assets/img/paypal.png'),
  unchecked: require('@assets/img/unchecked.png'),
  visa: require('@assets/img/visa.png'),
  card: require('@assets/img/card.png'),
  calendargray: require('@assets/img/calendargray.png'),
  clock: require('@assets/img/clock.png'),
  ticket: require('@assets/img/ticket.png'),
  mappin: require('@assets/img/mappin.png'),

  memories1: require('@assets/img/memories1.png'),
  memories2: require('@assets/img/memories2.png'),
  event1: require('@assets/img/event1.png'),
  event2: require('@assets/img/event2.png'),
  event3: require('@assets/img/event3.png'),
  upcomingEvent1: require('@assets/img/upcomingEvent1.png'),
  upcomingEvent2: require('@assets/img/upcomingEvent2.png'),

  verify: require('@assets/img/verify.png'),
  books: require('@assets/img/books.png'),
  movies: require('@assets/img/movies.png'),
  music: require('@assets/img/music.png'),
  livemarker: require('@assets/img/livemarker.png'),
  fifaresume: require('@assets/img/fifaresume.png'),
};

export default AppImages;
