import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
  },
  backGroundImage: {
    width: wp('100%'),
    resizeMode: 'cover',
    position: 'absolute',
  },
  overlay: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  followTitleContainer: {
    width: '100%',
    height: '60%',
    marginLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  createFollowText: {
    color: 'white',
    fontSize: 25,
    fontWeight: 'bold',
    marginLeft: '1%',
  },
  closeIcon: {
    width: '90%',
    height: '90%',
    resizeMode: 'contain',
    right: 0,
    marginRight: '5%',
  },
  closeIconView: {
    height: '60%',
    justifyContent: 'flex-end',
    position: 'absolute',
    right: 20,
    marginRight: '5%',
  },
  followMainView: {
    height: hp('100%'),
    borderWidth: 1,
  },
  bottomView: {
    flex: 1,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    backgroundColor: '#F8F8F8',
  },
  descriptionView: {
    width: wp('90%'),
    marginTop: '5%',
    aspectRatio: 7,
    borderColor: '#DEDEDE',
    borderWidth: 1,
    borderRadius: 15,
    paddingLeft: 10,
    marginLeft: '5%',
    marginRight: '5%',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 2,
    shadowOffset: {
      height: 0.5,
      width: 0.5,
    },
    justifyContent: 'center',
  },
  followTxt: {
    flex: 1,
    fontSize: 12,
    marginRight: 15,
  },
  searchIcon: {
    width: wp('3%'),
    height: hp('3%'),
    resizeMode: 'contain',
    justifyContent: 'flex-end',
    position: 'absolute',
    right: 0,
    marginRight: '3%',
  },
  listContainer: {
    flex: 1,
    marginTop: '5%',
    marginLeft: '3%',
    marginRight: '3%',
  },
  list: {
    paddingVertical: 15,
    margin: 5,
  },
  userName: {
    color: '#13153B',
    fontSize: 12,
    fontFamily: 'Poppins-SemiBold',
  },
  petName: {
    color: '#8895AA',
    fontSize: 10,
    fontFamily: 'Poppins-Medium',
  },
  acceptMainView: {
    backgroundColor: '#FF2485',
    borderRadius: 20,
    width: '45%',
    aspectRatio: 2.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  acceptText: {
    color: 'white',
    fontSize: 10,
    fontFamily: 'Poppins-Medium',
  },
  deleteMainView: {
    borderColor: '#FF2485',
    borderWidth: 1,
    borderRadius: 40,
    width: 110,
    height: 45,
    aspectRatio: 2.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 40,
  },
  deleteMainViewText: {
    color: 'black',
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
  },
  followReqItemView: {
    flexDirection: 'row',
    width: '100%',
  },
  followReqItemProfileView: {
    height: 55,
    aspectRatio: 1,
    borderRadius: 27.5,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginRight: 10,
  },
  followReqItemProfileImg: {
    width: 60,
    height: 60,
    borderRadius: 60 / 2,
  },
  followReqItemTextView: {
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    width: '40%',
  },
  followReqItemAcptORDeleteView: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
});
