export const GET_USER_REQUEST = 'event/GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'event/GET_USER_SUCCESS';
export const GET_USER_FAILED = 'event/GET_USER_FAILED';
export const GET_RECOMMENDED_USERS_REQUEST =
  'event/GET_RECOMMENDED_USERS_REQUEST';
export const GET_RECOMMENDED_USERS_SUCCESS =
  'event/GET_RECOMMENDED_USERS_SUCCESS';
export const GET_RECOMMENDED_USERS_FAILED =
  'event/GET_RECOMMENDED_USERS_FAILED';
