import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  textWrapper: {
    height: hp('100%'),
    width: wp('100%'),
  },
  BackImage: {
    width: wp('100%'),
    height: hp('50%'),
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    overflow: 'hidden',
  },
  Backcontainer: {
    width: wp('100%'),
    height: hp('50%'),
  },
  overlay: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    position: 'absolute',
  },
  overlayTimeNTitle: {
    height: '30%',
    left: 0,
    right: 0,
    bottom: 35,
    position: 'absolute',
    flexDirection: 'column-reverse',
  },
  ShareAndCloseContainer: {
    flex: 1,
    width: wp('100%'),
    marginTop: '15%',
    flexDirection: 'row',
  },
  ShareIcon: {
    width: wp('6%'),
    height: hp('4%'),
    resizeMode: 'contain',
    justifyContent: 'flex-start',
  },
  CloseIcon: {
    width: wp('6%'),
    height: hp('4%'),
    resizeMode: 'contain',
    justifyContent: 'flex-end',
  },
  ShareMainView: {
    height: hp('6%'),
    width: wp('40%'),
    marginTop: '24%',
    flexDirection: 'row',
    marginLeft: '10%',
  },
  ShareView: {
    height: hp('7%'),
    width: wp('25%'),
    backgroundColor: '#F8F8F8',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: '#F8F8F8',
  },
  ShareChildView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  SocialIconContainer: {
    flex: 1,
    alignItems: 'center',
  },
  TitleContainer: {
    width: wp('100%'),
    marginTop: '40%',
    flexDirection: 'column',
  },
  DateTimeText: {
    color: 'white',
    fontSize: 16,
    fontStyle: 'normal',
    fontFamily: 'Gilroy-ExtraBold',
  },
  ClubNAmeText: {
    color: 'white',
    fontSize: 30,
    fontStyle: 'normal',
    fontFamily: 'Gilroy-ExtraBold',
  },
  MapContainer: {
    marginHorizontal: 0,
    width: '100%',
    aspectRatio: 3.5,
    marginTop: -30,
  },
  MapView: {
    backgroundColor: 'pink',
    width: '90%',
    height: '100%',
    alignSelf: 'center',
    borderRadius: 10,
    overflow:'hidden'
  },
  standardPriceView: {
    marginHorizontal: 0,
    width: '100%',
    aspectRatio: 12,
    marginTop: 0,
    justifyContent: 'center',
  },
  standardPriceText: {
    marginRight: '5%',
    alignSelf: 'flex-end',
    borderRadius: 10,
    fontFamily: 'Gilroy-SemiBold',
    color: '#2B2424',
  },
  AboutTextContainer: {
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: 0,
  },
  AboutText: {
    fontSize: 16,
    color: '#2B2424',
    fontFamily: 'Gilroy-SemiBold',
  },
  AboutDescription: {
    marginTop: '3%',
    fontSize: 12,
    color: '#707070',
    fontFamily: 'Poppins-Medium',
  },
  OtherDetailTextContainer: {
    flex: 1,
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: '5%',
  },
  OtherDetailText: {
    fontSize: 16,
    color: '#2B2424',
    fontFamily: 'Gilroy-SemiBold',
  },
  DetailText: {
    flex: 1,
    flexDirection: 'row',
    marginTop: '3%',
    alignItems: 'center',
  },
  FirstDots: {
    color: '#FF2485',
  },
  TextDots: {
    color: '#707070',
    fontSize: 16,
    marginLeft: '2%',
    fontFamily: 'Gilroy-Medium',
  },
  ExtrasTextContainer: {
    flex: 1,
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: '5%',
  },
  ExtrasText: {
    fontSize: 16,
    color: 'black',
    fontFamily: 'Gilroy-SemiBold',
  },
  ExtrasInsideFirstView: {
    width: wp('100%'),
    flexDirection: 'row',
    marginTop: '3%',
    alignItems: 'center',
  },
  UnlmitedAlcoholText: {
    color: '#707070',
    fontSize: 14,
    fontFamily: 'Gilroy-Medium',
    marginLeft: '2%',
  },
  UnlmitedAlcoholPriceText: {
    color: '#2B2424',
    fontSize: 16,
    fontFamily: 'Gilroy-SemiBold',
    position: 'absolute',
    right: '10%',
  },
  ExtrasInsideSecondView: {
    width: wp('100%'),
    flexDirection: 'row',
    marginTop: '3%',
    alignItems: 'center',
  },
  AddMorePepoleText: {
    color: '#707070',
    fontSize: 14,
    fontWeight: 'normal',
    marginLeft: '2%',
    fontFamily: 'Gilroy-Medium',
  },
  PersonPriceText: {
    color: '#2B2424',
    fontSize: 16,
    fontWeight: 'normal',
    position: 'absolute',
    right: '10%',
  },
  IncrAndDecrMianView: {
    marginTop: '5%',
    marginLeft: '5%',
    marginRight: '5%',
    width: wp('30%'),
    backgroundColor: '#E6E6E6',
    borderRadius: 20,
  },
  IncrAndDecrChildView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 30,
  },
  IncrAndDecrTextView: {
    color: '#BEBEBE',
    fontSize: 16,
    alignSelf: 'center',
    marginLeft: 10,
    marginRight: 10,
    fontFamily: 'Gilroy-Medium',
  },
  TotalTextContainer: {
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: '5%',
    marginBottom: '5%',
  },
  TotalText: {
    fontSize: 16,
    color: 'black',
    fontFamily: 'Gilroy-SemiBold',
  },
  TotalchildView: {
    flexDirection: 'row',
    marginTop: '3%',
    height: 50,
    alignContent: 'center',
    alignItems: 'center',
  },
  TotalPriceText: {
    color: '#2B2424',
    fontSize: 32,
    fontFamily: 'Gilroy-Bold',
    marginTop: '2.5%',
  },
  LeftBorderView: {
    width: '20%',
    height: '50%',
    marginLeft: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF2485',
  },
  BorderInsideTextView: {
    color: '#FF2485',
    textAlign: 'center',
    fontSize: 12,
    marginTop: 1,
    marginLeft: 20,
    borderColor: '#FF2485',
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 2,
    borderRadius: 10,
  },
  BUY: {
    height: '55%',
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FF2485',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FF2485',
    position: 'absolute',
    right: 10,
    justifyContent: 'center',
  },
  BuyText: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Gilroy-Medium',
    height: '55%',
    paddingHorizontal: 20,
    paddingVertical: 5,
    backgroundColor: '#FF2485',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#FF2485',
    position: 'absolute',
    right: 10,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  shareIconView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: '5%',
  },
  closeIconView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight: '5%',
  },
  timeView: {
    justifyContent: 'flex-start',
    marginLeft: '5%',
  },
  eventNameView: {
    justifyContent: 'flex-start',
    marginLeft: '5%',
    marginTop: 10,
  },
  decrementButtonView: {
    position: 'absolute',
    left: 0,
    height: '95%',
    aspectRatio: 1,
  },
  incrementButtonView: {
    position: 'absolute',
    right: 0,
    height: '95%',
    aspectRatio: 1,
  },
});
