export const GET_MEMORIES_REQUEST = 'memories/GET_MEMORIES_REQUEST';
export const GET_MEMORIES_SUCCESS = 'memories/GET_MEMORIES_SUCCESS';
export const GET_MEMORIES_FAILED = 'memories/GET_MEMORIES_FAILED';

export const GET_COMMENTS_BY_MEMORY_ID_REQUEST = 'memories/GET_COMMENTS_BY_MEMORY_ID_REQUEST';
export const GET_COMMENTS_BY_MEMORY_ID_SUCCESS = 'memories/GET_COMMENTS_BY_MEMORY_ID_SUCCESS';
export const GET_COMMENTS_BY_MEMORY_ID_FAILED = 'memories/GET_COMMENTS_BY_MEMORY_ID_FAILED'; 