import { StyleSheet } from 'react-native';
import { getStatusBarHeight } from 'react-native-status-bar-height';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  shareButtonView: {
    marginLeft: 20,
    aspectRatio: 1,
    height: '30%',
  },
  headerMainView: {
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    marginTop: getStatusBarHeight(),
    width: '100%',
    height: '10%',
  },
  shareImg: {
    width: '100%',
    height: '100%',
  },
  ticketImg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  closeButtonView: {
    marginRight: 20,
    aspectRatio: 1,
    height: '30%',
  },
  closeButtonMainView: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  heartButtonMainView: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  heartButtonView: {
    marginRight: 23,
    aspectRatio: 1,
    height: '33%',
  },
  eventImageView: {
    position: 'absolute',
    width: '100%',
    aspectRatio: 1.1,
    backgroundColor: 'pink',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    overflow: 'hidden',
  },
  eventImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'pink',
  },
  ticketMainView: {
    marginHorizontal: 25,
    aspectRatio: 0.71,
  },
  ticketTitleNTimeView: {
    width: '100%',
    aspectRatio: 2.22,
  },
  ticketTimeView: {
    marginHorizontal: 30,
    paddingTop: 5,
    height: '30%',
    justifyContent: 'center',
  },
  ticketTimeText: {
    fontSize: 16,
    fontFamily: 'Gilroy-ExtraBold',
    color: '#FF2485',
  },
  ticketTitleView: {
    marginHorizontal: 30,
    height: '70%',
  },
  ticketTitleText: {
    fontSize: 35,
    fontFamily: 'Gilroy-ExtraBold',
  },
  ticketbottomView: {
    marginHorizontal: 30,
    marginTop: 10,
    flex: 1,
  },
  ticketTypeView: {
    width: '100%',
    height: '25%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketTypeText: {
    color: '#FF2485',
    borderWidth: 1,
    borderColor: '#FF2485',
    borderRadius: 12,
    overflow: 'hidden',
    fontSize: 14,
    paddingHorizontal: 14,
    paddingVertical: 2,
    fontFamily: 'Gilroy-Medium',
  },
  ticketEntryNExtrasView: {
    width: '100%',
    height: '30%',
    flexDirection: 'row',
  },
  ticketEntryMainView: {
    width: '55%',
    height: '100%',
    flexDirection: 'column',
  },
  ticketEntryTitleView: {
    width: '100%',
    height: '40%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  ticketEntryImage: {
    width: '16%',
    aspectRatio: 1,
  },
  ticketEntryTitleText: {
    flex: 1,
    marginLeft: 15,
    fontSize: 18,
    fontFamily: 'Gilroy-SemiBold',
  },
  ticketEntryAnsView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketEntryAnsText: {
    width: '100%',
    fontSize: 15,
    marginTop: '5%',
    fontFamily: 'Gilroy-Medium',
    textAlign: 'left',
    color: '#707070',
  },
  ticketExtrasMainView: {
    width: '45%',
    height: '100%',
    flexDirection: 'column',
  },
  ticketExtrasTitleView: {
    width: '100%',
    height: '40%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  ticketExtrasTitleImage: {
    width: '18.5%',
    aspectRatio: 1,
  },
  ticketExtrasTitleText: {
    flex: 1,
    marginLeft: 15,
    fontSize: 18,
    fontFamily: 'Gilroy-SemiBold',
  },
  ticketExtrasTitleAnsView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketExtrasTitleAnsText: {
    width: '100%',
    fontSize: 15,
    marginTop: '5%',
    fontFamily: 'Gilroy-Medium',
    textAlign: 'left',
    color: '#707070',
  },
  ticketIdMainView: {
    width: '100%',
    height: '45%',
  },
  ticketIdTitleText: {
    marginTop: 10,
    fontSize: 18,
    fontFamily: 'Gilroy-SemiBold',
    color: '#2B2424',
    width: '100%',
  },
  ticketIdText: {
    marginTop: 10,
    fontSize: 16,
    fontFamily: 'Gilroy-Medium',
    color: '#707070',
    width: '100%',
  },
  ticketBarcodeView: {
    marginTop: 10,
    width: '100%',
    height: '35%',
    backgroundColor: 'pink',
    overflow: 'hidden',
  },
  creditCardMainView: {
    justifyContent: 'center',
    marginHorizontal: 25,
    aspectRatio: 1.25,
  },
  creditCardView: {
    alignItems: 'center',
    aspectRatio: 1.75,
  },
  creditCardImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
    position: 'absolute',
  },
  creditCardNumberText: {
    color: 'white',
    marginTop: '30%',
    textAlign: 'center',
    height: '10%',
    width: '80%',
  },
  creditCardBottomSubView: {
    height: '25%',
    marginLeft: '5%',
    width: '74%',
    flexDirection: 'row',
  },
  creditCardNameView: {
    alignItems: 'center',
    height: '100%',
    width: '62%',
    flexDirection: 'row',
  },
  creditCardNameText: {
    flex: 1,
    color: 'white',
    fontWeight: '700',
  },
  creditCardExDateNCvcView: {
    flexDirection: 'column',
    height: '100%',
    width: '38%',
  },
  creditCardExDateView: {
    alignItems: 'center',
    height: '50%',
    width: '100%',
    flexDirection: 'row',
  },
  creditCardExDateText: {
    fontSize: 10,
    flex: 1,
    color: 'white',
    fontWeight: '700',
  },
  creditCardCvcView: {
    alignItems: 'center',
    height: '50%',
    width: '100%',
    flexDirection: 'row',
  },
  creditCardCvcText: {
    fontSize: 10,
    flex: 1,
    color: 'white',
    fontWeight: '700',
  },
  creditCardNPaypalBtnView: {
    marginHorizontal: 25,
    aspectRatio: 8,
    flexDirection: 'row',
  },
  creditCardBtnMainView: {
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginTop: 20,
    height: '100%',
    width: '45%',
  },
  creditCardBtnView: {
    flexDirection: 'row',
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
  creditCardCheckBtnView: {
    justifyContent: 'center',
    height: '100%',
    aspectRatio: 1,
    borderRadius: 5,
  },
  creditCardCheckImage: {
    resizeMode: 'contain',
    height: '60%',
    aspectRatio: 1,
    alignSelf: 'center',
  },
  creditCardBtnText: {
    alignSelf: 'center',
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Gilroy-SemiBold',
  },
  payPalBtnMainView: {
    justifyContent: 'center',
    marginLeft: '10%',
    height: '100%',
    marginTop: 20,
    width: '45%',
  },
  payPalBtnView: {
    flexDirection: 'row',
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
  paypalBtnImgView: {
    justifyContent: 'center',
    height: '100%',
    aspectRatio: 1,
    borderRadius: 5,
  },
  paypalBtnImage: {
    height: '60%',
    aspectRatio: 1,
  },
  paypalLogo: {
    height: '50%',
    width: '15%',
  },
  payPalBtnTxt: {
    alignSelf: 'center',
    flex: 1,
    fontFamily: 'Gilroy-SemiBold',
  },
  skrillBtnMainView: {
    top: 10,
    marginHorizontal: 25,
    aspectRatio: 8,
    flexDirection: 'row',
  },
  skrillBtnSubView: {
    justifyContent: 'center',
    alignSelf: 'flex-start',
    height: '100%',
    width: '45%',
  },
  skrillBtnView: {
    flexDirection: 'row',
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
  skrillBtnCheckImgView: {
    justifyContent: 'center',
    height: '100%',
    aspectRatio: 1,
    borderRadius: 5,
  },
  skrillBtnCheckImage: {
    resizeMode: 'contain',
    height: '60%',
    aspectRatio: 1,
    alignSelf: 'center',
  },
  skrillBtnText: {
    alignSelf: 'center',
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Gilroy-SemiBold',
  },
  cardInformationText: {
    fontSize: 20,
    alignSelf: 'flex-start',
    marginHorizontal: 25,
    marginTop: 40,
    textAlign: 'center',
    fontFamily: 'Gilroy-ExtraBold',
  },
  nameTextInputView: {
    borderColor: '#DEDEDE',
    borderRadius: 10,
    backgroundColor: 'white',
    marginHorizontal: 25,
    marginTop: 15,
    height: 45,
    textAlign: 'center',
  },
  nameTextInput: {
    fontSize: 15,
    flex: 1,
    marginHorizontal: 15,
    fontFamily: 'Gilroy-Medium',
  },
  cardNoTextInputView: {
    flexDirection: 'row',
    borderColor: '#DEDEDE',
    borderRadius: 10,
    backgroundColor: 'white',
    marginHorizontal: 25,
    marginTop: 15,
    height: 45,
  },
  cardNoTextInput: {
    fontSize: 15,
    flex: 1,
    marginLeft: 15,
    fontFamily: 'Gilroy-Medium',
  },
  visaImage: {
    resizeMode: 'contain',
    height: '80%',
    width: '10%',
    marginHorizontal: 15,
    alignSelf: 'center',
  },
  cvcNExpDate: {
    marginHorizontal: 25,
    flexDirection: 'row',
    height: 50,
    marginTop: 15,
  },
  cvcView: {
    justifyContent: 'center',
    alignSelf: 'flex-start',
    height: '100%',
    width: '47.5%',
  },
  cvcTextInputView: {
    flexDirection: 'row',
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
  cvcTextInput: {
    fontSize: 15,
    flex: 1,
    marginLeft: 15,
    fontFamily: 'Gilroy-Medium',
  },
  exDateView: {
    justifyContent: 'center',
    marginLeft: '5%',
    height: '100%',
    width: '47.5%',
  },
  exDateTextInputView: {
    flexDirection: 'row',
    height: '90%',
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
  exDateTextInput: {
    fontSize: 15,
    flex: 1,
    marginLeft: 15,
    fontFamily: 'Gilroy-Medium',
  },
  cardSaveView: {
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 25,
    height: 30,
    marginTop: 25,
  },
  cardSaveCheckMarkImage: {
    height: '90%',
    aspectRatio: 1,
    borderRadius: 7,
    borderColor: 'gray',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardSaveTextInput: {
    marginLeft: 15,
    fontFamily: 'Gilroy-Medium',
    color: '#707070',
  },
  completePaymentBtnView: {
    alignItems: 'center',
    width: '100%',
    aspectRatio: 10,
    marginTop: 60,
  },
  completePaymentBtnSubView: {
    flex: 1,
    justifyContent: 'center',
    height: '100%',
    backgroundColor: '#FF2485',
    borderRadius: 50,
  },
  CompletePaymentText: {
    width: '100%',
    paddingHorizontal: 20,
    color: 'white',
    fontFamily: 'Gilroy-Bold',
  },
  bottomSafeArea: {
    marginHorizontal: 25,
    height: 20,
  },
  cardDataView:{
    flex: 1
  }
});
