import {StyleSheet, Dimensions} from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const ITEM_WIDTH = Math.round(SCREEN_WIDTH * 0.9);
const ITEM_HEIGHT = Math.round(ITEM_WIDTH * 0.57);

export default StyleSheet.create({
  homeNavigationImg: {
    height: '35%',
    width: '100%',
    marginTop: 0,
    resizeMode: 'cover',
  },
  menuImg: {
    width: '50%',
    height: '35%',
    alignSelf: 'flex-end',
  },
  memoriesHeartView: {
    marginTop: 8,
    aspectRatio: 1.18,
    height: '55%',
  },
  memoriesHeartImg: {
    flex: 1,
    resizeMode: 'center',
  },
  memoriesLikesCountView: {
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  memoriesLikesCountTxt: {
    color: '#8895AA',
    marginTop: 9,
    marginLeft: 10,
    textAlign: 'center',
    fontSize: 13,
    fontFamily: 'Poppins-SemiBold',
  },
  memoriesNameNTimeView: {
    marginLeft: 14,
    flex: 1,
    height: '100%',
    alignSelf: 'flex-start',
  },
  memoriesProfileNameView: {
    width: '100%',
    height: '60%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  memoriesProfileNameTxt: {
    color: '#121212',
    width: '100%',
    fontSize: 16,
    fontFamily: 'Gilroy-Bold',
  },
  memoriesTimeView: {
    width: '100%',
    height: '50%',
    justifyContent: 'center',
  },
  memoriesTimeText: {
    color: '#8895AA',
    width: '100%',
    fontSize: 10,
  },
  UpcomingEventTypeMainView: {
    width: '100%',
    height: '20%',
    justifyContent: 'center',
  },
  UpcomingEventTypeView: {
    marginLeft: 12,
    borderRadius: 10,
    paddingVertical: 3,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    backgroundColor: '#rgba(255,255,255,0.53)',
    color: '#FF2485',
    textAlign: 'center',
    overflow: 'hidden',
    fontSize: 10,
    fontFamily: 'Gilroy-ExtraBold',
  },
  UpcomingEventTypeText: {
    padding: 0,
    height: '100%',
    width: '100%',
    textAlign: 'center',
    color: '#FF2485',
    fontWeight: '400',
    justifyContent: 'center',
  },
  upcomingEvetsBackImg: {
    height: '100%',
    width: '100%',
  },
  upcomingEvetsTimeNTitleView: {
    width: '100%',
    height: '80%',
    alignItems: 'flex-end',
    flexDirection: 'column-reverse',
  },
  upcomingEvetsTimeView: {
    marginLeft: 10,
    width: '100%',
    height: '10%',
    justifyContent: 'center',
  },
  upcomingEvetsTimeTxt: {
    width: '95%',
    textAlign: 'left',
    color: '#fff',
    fontSize: 12,
    fontFamily: 'Gilroy-ExtraBold',
  },
  upcomingEvetsTitleView: {
    marginLeft: 10,
    height: '35%',
    justifyContent: 'flex-start',
  },
  upcomingEvetsTitleText: {
    width: '95%',
    color: 'white',
    fontSize: 16,
    fontFamily: 'Gilroy-ExtraBold',
    textAlign: 'left',
    marginBottom: 10,
  },
  bottomTabSpace: {
    width: '100%',
    height: 80,
    backgroundColor: 'rgba(0,0,0,0)',
  },
  memorisBottomLikesView: {
    flexDirection: 'row-reverse',
    width: '26%',
    height: '100%',
    alignSelf: 'flex-start',
  },
  commentsCountTxt: {
    color: '#8895AA',
    marginTop: 9,
    marginLeft: 10,
    textAlign: 'center',
    fontSize: 13,
    fontFamily: 'Poppins-SemiBold',
  },
  commentsCountView: {
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  commentsImage: {
    flex: 1,
    resizeMode: 'center',
  },
  memorisBottomCommentView: {
    flexDirection: 'row-reverse',
    width: '25%',
    height: '100%',
    justifyContent: 'center',
  },
  memoriesBottomSecondView: {
    flexDirection: 'row-reverse',
    flex: 1,
    alignContent: 'flex-start',
  },
  memoriesBottomProfileView: {
    aspectRatio: 1,
    borderRadius: 50,
    overflow: 'hidden',
    height: '100%',
    justifyContent: 'center',
  },
  memoriesBottomFirstView: {
    flexDirection: 'row',
    width: '100%',
    height: '50%',
    justifyContent: 'center',
  },
  memoriesBottomMainView: {
    width: '100%',
    height: '20%',
    justifyContent: 'flex-end',
  },
  memoriesMainView: {
    borderRadius: 22,
    overflow: 'hidden',
    width: '100%',
    height: '80%',
    justifyContent: 'center',
  },
  viewMenu: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
  },
  pagerEventTitleTxt: {
    height: '100%',
    width: '100%',
    color: 'white',
    fontSize: 18,
    fontFamily: 'Gilroy-ExtraBold',
  },
  pagerEventTitle: {
    marginLeft: 10,
    height: '35%',
    justifyContent: 'flex-start',
  },
  pagerTimeText: {
    padding: 0,
    height: '100%',
    width: '100%',
    color: '#fff',
    fontSize: 11,
    fontFamily: 'Gilroy-ExtraBold',
  },
  pagerTimeView: {
    marginLeft: 10,
    width: '100%',
    height: '10%',
    justifyContent: 'center',
  },
  pagerBottomSubView: {
    width: '100%',
    height: '85%',
    justifyContent: 'flex-end',
  },
  pagerEventTypeView: {
    marginLeft: 14,
    borderRadius: 10,
    paddingVertical: 3,
    paddingHorizontal: 10,
    marginTop: 12,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    backgroundColor: '#DEA301',
    color: 'white',
    textAlign: 'center',
    overflow: 'hidden',
    fontSize: 10,
    fontFamily: 'Gilroy-ExtraBold',
  },
  pagerEventTypeMainView: {
    width: '100%',
    height: '15%',
  },
  viewUpcomingEvent: {
    width: Math.round(SCREEN_WIDTH * 0.5),
    height: Math.round(SCREEN_WIDTH * 0.6),
    justifyContent: 'center',
    backgroundColor: 'dodgerblue',
    borderRadius: 10,
    marginLeft: 20,
    overflow: 'hidden',
  },
  mainViewUpcomingEvent: {
    flexDirection: 'row',
    width: Math.round(SCREEN_WIDTH),
    height: Math.round(SCREEN_WIDTH * 0.6),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 15,
  },
  viewMemories: {
    width: Math.round(SCREEN_WIDTH - 40),
    marginBottom: 30,
    height: Math.round((SCREEN_WIDTH - 40) * 1.12),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  text: {
    color: '#4f603c',
  },
  explore: {
    justifyContent: 'center',
    height: '100%',
    marginLeft: 20,
    fontSize: 30,
  },
  menu: {
    justifyContent: 'center',
    height: '100%',
    aspectRatio: 1,
    marginRight: 20,
    alignSelf: 'flex-end',
  },
  exploretext: {
    fontSize: 30,
    color: 'white',
    fontFamily: 'Gilroy-Bold',
  },
  viewHeader: {
    height: 64,
    width: '100%',
    marginTop: 0,
    flexDirection: 'row',
  },
  eventForYouText: {
    fontSize: 20,
    color: 'white',
    fontFamily: 'Gilroy-SemiBold',
  },
  memoriesText: {
    fontSize: 20,
    color: 'black',
    fontWeight: '400',
    fontFamily: 'Gilroy-SemiBold',
  },
  viewEventForYou: {
    height: 30,
    width: '100%',
    marginTop: 0,
  },
  headerMemories: {
    height: 70,
    width: '100%',
    marginTop: 15,
  },
  headerUpcomingEvent: {
    height: 50,
    width: '100%',
    marginTop: 0,
  },
  backImage: {
    aspectRatio: 0.57,
    width: '100%',
    overflow: 'hidden',
    position: 'absolute',
  },
  pagerbackImage: {
    height: '100%',
    width: '100%',
    overflow: 'hidden',
    borderRadius: 10,
  },
  viewSwiper: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    backgroundColor: '#rgba(0,0,0,0)',
  },
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  carouselContainer: {
    marginTop: 10,
    height: ITEM_HEIGHT,
  },
  itemContainer: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 10,
  },
  itemLabel: {
    color: 'white',
    fontSize: 24,
  },
  counter: {
    marginTop: 25,
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
