import { StyleSheet, Dimensions } from 'react-native';
import { getStatusBarHeight } from 'react-native-status-bar-height';
const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN = Dimensions.get('window');

export default StyleSheet.create({
  mainScreenView: {
    height: '100%',
    width: '100%',
    backgroundColor: '#F8F8F8',
  },
  filledHeartImage: {
    height: '100%',
    width: '100%',
  },
  mainScreenSubView: {
    height: '100%',
    width: '100%',
    flexDirection: 'column-reverse',
  },
  sendImage: {
    height: '100%',
    width: '100%',
  },
  commentsText: {
    marginLeft: 20,
    fontSize: 17,
    fontFamily: 'Gilroy-Bold',
    color: 'white',
  },
  commentsImageView: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '40%',
  },
  commentContainer: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginVertical: 15
  },
  commentAvatarContainer: {
    backgroundColor: 'white',
    borderRadius: 100,
    padding: 2
  },
  commentDetailsContainer: {
    flex: 1,
    paddingHorizontal: 10
  },
  commentOwnerText: {
    fontSize: 10,
    lineHeight: 16,
    fontFamily: 'Poppins-SemiBold',
  },
  commentDescText: {
    fontSize: 14,
    lineHeight: 16,
    fontFamily: 'Gilroy-Bold',
  },
  commentLikesText: {
    fontFamily: 'Poppins-Light',
    fontSize: 10,
    color: '#8895AA',
  },
  commentLikeImage: { width: 14, aspectRatio: 1 },
  filledHeartImageView: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '40%',
  },
  filledHeartMainImage: {
    height: '75%',
    aspectRatio: 1,
  },
  mainView: {
    flex: 1,
  },
  inputContent: {
    marginHorizontal: 16,
    marginVertical: 8,
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 25,
  },
  sendIcon: {
    width: 35,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 7,
  },
  cellMsgText: {
    color: '#8895AA',
    height: '100%',
    width: '100%',
    fontFamily: 'Gilroy-Bold',
    fontSize: 14,
  },
  cellTimeText: {
    color: '#8895AA',
    height: '100%',
    width: '100%',
    fontFamily: 'Poppins-Light',
    fontSize: 10,
  },
  cellMsgMainView: {
    width: '100%',
    height: '32.5%',
    justifyContent: 'center',
  },
  cellUserText: {
    color: '#000000',
    padding: 0,
    height: '100%',
    width: '100%',
    fontSize: 12,
    fontFamily: 'Poppins-SemiBold',
  },
  cellUserNameView: {
    width: '100%',
    height: '35%',
    justifyContent: 'flex-start',
  },
  cellCenterMainView: {
    marginLeft: 8,
    flex: 1,
    height: '100%',
    alignSelf: 'flex-start',
  },
  cellTimeView: {
    width: '100%',
    height: '32.5%',
    justifyContent: 'flex-start',
  },
  cellLikeView: {
    aspectRatio: 1,
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    alignItems: 'center',
  },
  cellRightMainView: {
    flexDirection: 'row-reverse',
    flex: 1,
    alignContent: 'flex-start',
  },
  cellProfileImage: {
    aspectRatio: 1,
    borderRadius: 50,
    overflow: 'visible',
    height: '80%',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cellProfileView: {
    flexDirection: 'row',
    width: '100%',
    height: 60,
    justifyContent: 'center',
  },
  mainCellView: {
    width: '100%',
    height: 100,
    justifyContent: 'center',
  },
  memorisBottomLikesView: {
    flexDirection: 'row',
    width: '20%',
    height: '100%',
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  commentsCountTxt: {
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Gilroy-SemiBold',
    marginTop: SCREEN.height * 0.008,
    marginLeft: SCREEN.height * 0.015,
    fontSize: SCREEN.height * 0.015,
  },
  commentsCountView: {
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: '70%',
  },
  commentsImage: {
    height: '80%',
    aspectRatio: 1,
  },
  memorisBottomCommentView: {
    flexDirection: 'row',
    width: '20%',
    height: '100%',
    justifyContent: 'center',
  },
  memoriesBottomSecondView: {
    flexDirection: 'row-reverse',
    flex: 1,
    alignContent: 'flex-start',
  },
  memoriesBottomProfileView: {
    aspectRatio: 1,
    borderRadius: 50,
    overflow: 'hidden',
    height: SCREEN.height * 0.05,
    justifyContent: 'center',
    marginTop: SCREEN.height * 0.002,
    marginLeft: 10,
  },
  memoriesBottomFirstView: {
    flexDirection: 'row',
    width: '100%',
    height: '75%',
    justifyContent: 'center',
  },
  memoriesBottomMainView: {
    alignItems: 'center',
    alignContent: 'center',
    flex: 1,
    marginVertical: 15,
    marginHorizontal: 15,
    flexDirection: 'row',
  },
  keyboardDissmiss: {
    height: '100%',
    width: '100%',
    // backgroundColor: '#13153B',
  },
  postlikeCountView: {
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: '70%',
  },
  postlikeCountTxt: {
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Gilroy-SemiBold',
    marginTop: SCREEN.height * 0.008,
    marginLeft: SCREEN.height * 0.015,
    marginRight: SCREEN.height * 0.01,
    fontSize: SCREEN.height * 0.015,
  },
  postNameMainView: {
    marginLeft: 8,
    flex: 1,
    height: '100%',
    alignSelf: 'flex-start',
  },
  postNameView: {
    width: '100%',
    height: '65%',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
  },
  postNameTxt: {
    color: 'white',
    fontFamily: 'Gilroy-Bold',
    fontSize: SCREEN.height * 0.02,
  },
  postTimeView: {
    width: '100%',
    height: '40%',
    justifyContent: 'center',
    // backgroundColor: 'black',
  },
  postTimeTxt: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Poppins-Light',
    marginTop: -2,
  },
  commentsFlatList: {
    width: '100%',
    height: '40%',
    paddingRight: 10,
    paddingLeft: 10,
  },
  inputProfileView: {
    height: 30,
    width: 30,
    backgroundColor: '#CF326F',
    marginLeft: 8,
    borderRadius: 100,
    overflow:'hidden'
  },
  textInputCommentMainView: {
    height: 50,
    width: SCREEN_WIDTH - 32 - 24 - 50 - 30,
    marginLeft: 8,
    borderRadius: 25,
  },
  textinputComment: {
    height: '100%',
    width: '96%',
    alignSelf: 'center',
    color: 'black',
  },
  memoriesMainView: {
    width: '100%',
    height: '60%',
    backgroundColor: '#7D00E7',
    borderBottomRightRadius: 40,
    borderBottomLeftRadius: 40,
    overflow: 'hidden',
  },
  memoriesImageView: {
    width: '100%',
    height: '80%',
    borderBottomRightRadius: 40,
    borderBottomLeftRadius: 40,
    overflow: 'hidden',
  },
  memoriesImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  headerMainView: {
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    marginTop: getStatusBarHeight(),
    width: '100%',
    height: '20%',
  },
  BackButtonView: {
    marginLeft: 20,
    aspectRatio: 1,
    height: '30%',
  },
  backArrowImg: {
    width: '100%',
    height: '100%',
  },
  cellLikeTouchableView: {
    height: '50%',
    aspectRatio: 1,
  },
});
